name: iPlayed
main: com.inspireVeiN.iPlayed.iPlayed
version: 0.8
author: VeiN
description: Track playtime and last activity time of players
commands:
    played:
        description: Check playtime and last activity
        usage: |
            /played                Check your playtime and last activity
            /played <player>    Check a player's playtime and last activity
    InspirePlayed:
        description: Check playtime and last activity
        usage: |
            /iPlayed load        Force load data from file
            /iPlayed save        Force save data to file
            /iPlayed version    Check iPlayed's version