name: InspirePlayed
main: com.gmail.melvinchien.InspirePlayed.InspirePlayed
version: 0.3

commands:
    played:
        description: See how much time a player has played on this server
        usage: |
            InspirePlayed Commands:
            /played                Check your playtime
            /played <player>    Check another player's playtime