name: InspirePlayed
main: com.gmail.melvinchien.InspirePlayed.InspirePlayed
version: 0.1

commands:
    pos:
        description: blah
        usage: /pos
    debug:
        description: blah blah
        usage: /debug
