name: InspirePlayed
main: com.gmail.melvinchien.InspirePlayed.InspirePlayed
version: 0.45

commands:
    played:
        description: Track playtime and last activity time of players
        usage: |
            InspirePlayed Commands:
            /played                Check your playtime and last activity
            /played <player>    Check another player's playtime and last activity