name: InspirePlayed
main: com.gmail.melvinchien.InspirePlayed.InspirePlayed
version: 0.1

commands:
    played:
        description: See how much time a player has played on this server
        usage: |
            InspirePlayed Help:
            /played
            /played <player>